server:
  port: 8080
  debug: true

feishu:
  app_id: "cli_a92a462044791bd6"
  app_secret: "Mh3AQKyT0x4VyfIuPq3LpcKjbC6kP5KE"
  verification_token: "xxxxxxxx" # 用于校验回调请求
  event_encrypt_key: "" # 如果开启了加密则填写

qq:
  bot_id: "xxxx"
  token: "xxxx"
  secret: "xxxx"

openclaw:
  api_url: "http://119.45.237.47:18789/v1"
  api_key: "sk-gCb5bYhfvehZzPtyOlFRjwgYcwG8rTMGLWxgDHh1WaqZEnwn"
